clearAllItemsFromBackpack player;
clearBackpackCargo player;
removeAllWeapons player;
removeAllItems player;
removeBackpack player;
removeHeadgear player;
removeUniform player;
removeVest player;
{player unassignItem _x;player removeItem _x} forEach assignedItems player;
player addHeadgear "442nd_Helmet";
player addUniform "SWOP_Clonetrooper_501_F_CombatUniform";
player addVest "SWOP_Clonetrooper_501_armor";
player addItem "itemCompass";
player addItem "itemWatch";
player addItem "tf_anprc152";
player addItem "itemMap";
player assignItem "itemCompass";
player assignItem "itemWatch";
player assignItem "tf_anprc152";
player assignItem "itemMap";
player addItem "OPTRE_NVG";
player assignItem "OPTRE_NVG";
player addItem "SWOP_Clones_HUD";
player assignItem "SWOP_Clones_HUD";
player addMagazine "SWOP_termDet_G";
player addMagazine "SWOP_termDet_G";
player addMagazine "Smokeshell";
player addMagazine "SWOP_DC15_Mag";
player addMagazine "SWOP_DC15_Mag";
player addMagazine "SWOP_DC15_Mag";
player addWeapon "SWOP_DC15";
player selectWeapon "SWOP_DC15";
player switchMove "amovpercmstpsraswrfldnon";
